import AsyncStorage from "@react-native-async-storage/async-storage";

/**
 * DEVICE STORAGE PERSISTENCE ENGINE (AuthStorage)
 * WHY IT'S DESIGNED AS A CLASS: Creating a class allows us to encapsulate storage transactions cleanly.
 * By using a constructor with a "namespace" configuration key, we prevent data keys from overwriting
 * other storage instances if we expand our local database storage requirements in the future.
 * * HOW IT WORKS: It abstracts raw device storage keys into explicit semantic helper operations
 * (`getAccessToken`, `setAccessToken`, `removeAccessToken`).
 */
class AuthStorage {
  // Instantiates isolation configurations for storage key pathways
  constructor(namespace = "auth") {
    this.namespace = namespace;
  }

  /**
   * RECOVER AUTHENTICATION TOKEN
   * WHY IT'S ASYNCHRONOUS: Reading from a mobile device's flash storage hardware memory is an I/O operation
   * that takes time. To keep the app UI interactive and fluid, we handle it as a non-blocking promise.
   * * @returns {String|null} The raw JWT string token value if found, or null if empty/expired.
   */
  async getAccessToken() {
    const token = await AsyncStorage.getItem(`${this.namespace}:token`);
    return token ? token : null;
  }

  /**
   * COMMIT PERSISTENT AUTHENTICATION TOKEN
   * WHY IT EXISTS: When useSignIn receives a valid token string from the server, it hands it
   * directly to this method to store it safely inside the phone's persistent storage files.
   * * @param {String} accessToken - The raw JWT token string generated by the Apollo Server.
   */
  async setAccessToken(accessToken) {
    await AsyncStorage.setItem(`${this.namespace}:token`, accessToken);
  }

  /**
   * PURGE AUTHENTICATION TOKEN (WIPE KEY)
   * WHY IT EXISTS: When a user chooses to log out via our useSignOut hook flow, calling this
   * method drops the explicit access token reference key entirely, putting the app back into an
   * anonymous guest permissions state profile.
   */
  async removeAccessToken() {
    await AsyncStorage.removeItem(`${this.namespace}:token`);
  }
}

export default AuthStorage;
